obj-$(CONFIG_INPUT_PRESS_NDT_F60) += ndt_f60.o
obj-$(CONFIG_INPUT_PRESS_NDT_M65) += ndt_m65.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT_MI)	+= atmel_mxt_ts_mi.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_FORCE) += synaptics_dsx_force/
obj-$(CONFIG_TOUCHSCREEN_ST_FTS_V521) += fts_521/
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_MI) += nt36xxx_mi/
obj-$(CONFIG_TOUCHSCREEN_FT5X46)  += ft5x46/
obj-$(CONFIG_TOUCHSCREEN_FTS_MI) += focaltech_touch_mi/

