ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/techpack/camera-sdm845/drivers/cam_smmu/
obj-$(CONFIG_SPECTRA_CAMERA) += 3dsl_eeprom_dev.o 3dsl_eeprom_core.o 3dsl_eeprom_soc.o
